fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: AdminBundle\Entity\User
    use_listener: false
    use_flash_notifications: true
    use_authentication_listener: true
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"