front:
    resource: "@FrontBundle/Controller/"
    type:     annotation
    prefix:   /

admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /easy-admin

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
